name: Deploy
on:
  push:
    branches:
      - main
env:
  AWS_REGION: ap-southeast-2
  REACT_APP_COGNITO_USER_POOL_ID: ${{ vars.REACT_APP_COGNITO_USER_POOL_ID }}
  REACT_APP_COGNITO_USER_POOL_APP_CLIENT_ID: ${{ vars.REACT_APP_COGNITO_USER_POOL_APP_CLIENT_ID }}

jobs:
  build:
    environment: dev
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - run: npm ci
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.IAM_ROLE }}
          aws-region: ap-southeast-2
      - run: |-
          export REACT_APP_BASE_URL=$(aws ssm get-parameter --name ${{ vars.API_ENDPOINT_PARAM }} --query Parameter.Value --output text)
          printenv
          npm run build --if-present
      - uses: actions/upload-artifact@v3
        with:
          name: build
          path: ./build
  deploy-dev:
    environment: dev
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.IAM_ROLE }}
          aws-region: ap-southeast-2
      - uses: actions/download-artifact@v3
        with:
          name: build
          path: ./build
      - run: ls
      - run: |-
          DEPLOY_BUCKET=$(aws ssm get-parameter --name ${{ vars.BUCKET_PARAM }} --query Parameter.Value --output text)
          printenv
          aws s3 sync ./build s3://$DEPLOY_BUCKET --delete

  deploy-staging:
    runs-on: ubuntu-latest
    needs: deploy-dev
    environment: Staging
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.IAM_ROLE }}
          aws-region: ap-southeast-2
      - uses: actions/download-artifact@v3
        with:
          name: build
          path: ./build
      - run: ls
      - run: |-
          DEPLOY_BUCKET=$(aws ssm get-parameter --name ${{ vars.BUCKET_PARAM }} --query Parameter.Value --output text)
          printenv
          aws s3 sync ./build s3://$DEPLOY_BUCKET --delete

  deploy-prod:
    runs-on: ubuntu-latest
    needs: deploy-staging
    environment: Prod
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.IAM_ROLE }}
          aws-region: ap-southeast-2
      - uses: actions/download-artifact@v3
        with:
          name: build
          path: ./build
      - run: ls
      - run: |-
          DEPLOY_BUCKET=$(aws ssm get-parameter --name ${{ vars.BUCKET_PARAM }} --query Parameter.Value --output text)
          aws s3 sync ./build s3://$DEPLOY_BUCKET --delete
